version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
      - MODEL_NAME=GradientBoosting
      - MODEL_VERSION=1
    depends_on:
      - mlflow
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.0
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0