name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linter (flake8)
      run: |
        flake8 src tests --max-line-length=88 --extend-ignore=E203

    - name: Run unit tests
      run: |
        pytest tests/data_test_processing.py -v